### ISSUE TITLE
event for notification of auth failures

### ISSUE THREAD

**Issue by mhassman** [auth0/socketio-jwt#26]
Hi, Is it possible to add an event callback for failures in socket-jwt.authorize? i.e. no token, invalid token, timer-initiated disconnect, etc.

I tried using a secondary middleware handler, but socketio-jwt doesn't pass the socket/connection along for additional handling.

**Comment by paramburu** [comment]
+1

**Comment by jfromaniello** [comment]
Server side or client side?

**Comment by drulia** [comment]
I'm currently struggling with this same thing. I'm loading the code and single page initial DOM from one server and then connecting socket.io to another server. On initial load, I have no way of knowing whether user is logged in or not. I was expecting that socket.on('error') will be called when I'm using outdated version of token, as per example on the Readme file, but it looks like it doesn't do that when using noQsMethodmethod, instead it simply disconnects socket instantly if wrong token was passed. But the reason the socket was disconnected is unknown, which could have happened because of internet problems, just as well.

So essentially it would be great if the socket.on('error') would work when using noQsMethod method, or something similar.

**Comment by jfromaniello** [comment]
> I was expecting that socket.on('error') will be called when I'm using outdated version of token

You can check the expiration client-side by using [jwt-decode](https://github.com/auth0/jwt-decode)

**Comment by drulia** [comment]
Yeah that might be a good option, but I would think it would still be reasonable to be able to properly validate the token on a server, as it might still be valid locally, not expired, but invalidated on the server if you're a using technique such as when user logs out, all its clients are logged out as well. I hope that makes sense.

Currently for testing purposes I've modified the code to emit 'auth_error' with the error (timeout or invalid_token) just before disconnecting the socket and it seems to be working quite well. If I find a token stored in users local storage, I try to authenticate user and in case this results in error, I can easily navigate user to the login page.

Do you think such feature would be possible to implement here, or you see some concerns about it?

**Comment by jfromaniello** [comment]
I think this is handled by #42
