### ISSUE TITLE
Why do you send the profile inside the token?

### ISSUE THREAD

**Issue by Carpetfizz** [auth0/socketio-jwt#31]
Hello,

In the file, `socketio-jwt/example/server.js:25` you have the following two lines:

     // We are sending the profile inside the token
      var token = jwt.sign(profile, jwt_secret, { expiresInMinutes: 60*5 });

What is the purpose of sending the entire profile if it can't be decoded on the client?

Thanks!

**Comment by jfromaniello** [comment]
it can be decoded on the client, check jwt-decode:

https://github.com/auth0/jwt-decode

JWTs are base64 encodded, and digital signed.

The reason I might want to send the profile some times inside the token, is because I need the profile on every request to set permissions and stuff., and I don't want to go to fetch it from the db.

**Comment by Carpetfizz** [comment]
Awesome, thank you so much!
