### ISSUE TITLE
namespace authentication

### ISSUE THREAD

**Issue by martineeez** [auth0/socketio-jwt#32]
hello, can this module also be used for namespace authentication?

**Comment by brentcobb** [comment]
Would love to see an example of this if it is possible.

**Comment by debhash** [comment]
```javascript
var admin = io.of('/admin').
    use(socketio_jwt.authorize({
      secret: jwt_secret,
      timeout: 15000,
      handshake: true
    })).
    on('connection', function (socket) {
       console.log('Hi');
});
```

**Comment by acydwarp** [comment]
Any example using a second roundtrip without the handshake? The following seems to be non-functional:

```
io.of('/namespace')
  .on('connection', socketioJwt.authorize({
    secret: 'key',
    timeout: 15000
  })).on('authenticated', function(socket) {
    console.log('hello!);
  }));
```

**Comment by netsgnut** [comment]
For now I am using something like:

```js
io.of('/namespace').on('connection', socketIoJwt.authorize({
  secret: 'key',
  timeout: 15000
}));
io.sockets.on('authenticated', function (socket) {
  console.log("Socket!");
});
```

**Comment by pist** [comment]
@debhash solution works, but it is not the best pattern when it comes to security.
@netsgnut solution doesn't work :( [text "Socket!" does not appear on console]

**Comment by nhahn** [comment]
I wasn't sure if this was discussed yet, but if you:
1. Have an existing connection to the server
2. Set authentication on another namespace (but not the original connection)
3. Use the handshake method
Authentication doesn't work. Because the socket.io manager tries to reuse the connection, the query isn't properly passed on to the socketIoJwt middleware. You have to manually set `multiplex` to false in order for the connection to be new and properly pass the authentication query.

**Comment by Root-Core** [comment]
I get the same issue as @nhahn, i have to deactivate `multiplex` in order to get the authentication working for namespaces.

I use the '/' namespace to do the login and all other namespaces use socketio-jwt.
Can this be fixed or is it an issue with socketio?

Regards!
